version: "3.7"

services:
  db:
    image: postgres
    container_name: 'colibri-postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: colibridb
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "54321:5432"
    volumes:
      - colibri_pgdb:/var/lib/postgresql/colibri_data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
        - postgres_network

  broker-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'colibri-rabbitmq'
    ports:
        - "56721:5672"
        - "56722:15672"
    networks:
        - rabbitmq_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: colibri-pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
        - postgres_network

volumes:
  colibri_pgdb:

networks:
  rabbitmq_network:
    driver: bridge
  postgres_network:
    driver: bridge

