apiVersion: v1
kind: Pod
metadata:
  name: colibri-api
  labels:
    tip: api
spec:
  containers:
    - image: daniellaion/colibri-api
      name: colibri-api
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      env:
      - name: NODE_ENV
        value: dev
      - name: PORT
        value: '3000'
      - name: PGHOST
        value: postgres-clusterip-service
      - name: PGUSER
        value: postgres
      - name: PGDATABASE
        value: colibridb
      - name: PGPASSWORD
        value: password
      - name: PGPORT
        value: '5432'
      - name: RABBITMQHOST
        value: amqp://rabbitmq-clusterip-service
      - name: JWT_SECRET_KEY
        value: myawesomeultrasecretkey
      - name: JWT_ISSUER
        value: colibri-webapp
      - name: JWT_SUBJECT
        value: 'Colibri Fast Token'
      - name: JWT_AUDIENCE
        value: postman

---
apiVersion: v1
kind: Service
metadata:
  name: api-nodeport-service
spec:
  selector:
    tip: api
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort