apiVersion: v1
kind: Pod
metadata:
  name: colibri-pgadmin
  labels:
    tip: pgadmin
spec:
  containers:
    - image: dpage/pgadmin4
      name: colibri-pgadmin
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: admin@admin.com
      - name: PGADMIN_DEFAULT_PASSWORD
        value: root
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-nodeport-service
spec:
  selector:
    run: pgadmin
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 80
  type: NodePort