apiVersion: v1
kind: Pod
metadata:
  name: colibri-rabbitmq
  labels:
    tip: rabbitmq
spec:
  containers:
    - image: rabbitmq:3-management-alpine
      name: colibri-rabbitmq
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip-service
spec:
  selector:
    tip: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport-service
spec:
  selector:
    tip: rabbitmq
  ports:
    - name: ui
      port: 56722
      targetPort: 15672
  type: NodePort